[features]
seeds = true
skip-lint = false

[programs.devnet]
plege = "4MHQj9xyrt9SDZiCt1awCLxveRYjdvGKTSftks7Uhxjb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha --require tests/utils/globalSetup.ts -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
types = "client/src/types/idl/"